version: '3'

networks:
  # enable connection with Traefik
  traefik:
    external: true
  # network for the app
  backend:
    external: true
    
services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - data:/var/www/html
    environment:
      - VIRTUAL_HOST=eos.zoness.me
      - LETSENCRYPT_HOST=eos.zoness.me
      - LETSENCRYPT_EMAIL=trevor@tlnprojects.com
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - traefik
      - backend

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  data:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/blockstorage/nextcloud
  certs:
  acme:
  vhost.d:
  html: