version: '3.1'

networks:
  # enable connection with Traefik
  traefik:
    external: true
  # network for the apps to reach
  backend:
    external: true
  nextcloud:
    external: true

services:
  app:
    image: phpmyadmin
    restart: always
    networks:
      - traefik
      - backend
      - nextcloud
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=https://pma.test
      - UPLOAD_LIMIT=256M
    labels:
      # The labels are useful for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Get the routes from http
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.test`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      # Redirect these routes to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.phpmyadmin.middlewares=redirect-to-https@docker"
      # Get the routes from https
      - "traefik.http.routers.phpmyadmin-secured.rule=Host(`pma.test`)"
      - "traefik.http.routers.phpmyadmin-secured.entrypoints=web-secure"
      # Apply autentificiation with http challenge
      - "traefik.http.routers.phpmyadmin-secured.tls=true"
      - "traefik.http.routers.phpmyadmin-secured.tls.certresolver=myhttpchallenge"
