version: '3.1'

services:
  db:
    image: mariadb:10.5
    restart: always
    env_file:
      - pma.env

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
